"""empty message

Revision ID: 05384023294d
Revises: 
Create Date: 2025-02-03 11:52:34.596068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05384023294d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Product_description', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.drop_column('Product_description')

    # ### end Alembic commands ###
