"""empty message

Revision ID: 09b50793de97
Revises: 05384023294d
Create Date: 2025-02-03 12:34:02.634975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b50793de97'
down_revision = '05384023294d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Category_isDeleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Category_Created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('Category_Modified_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.drop_column('Category_Modified_on')
        batch_op.drop_column('Category_Created_on')
        batch_op.drop_column('Category_isDeleted')

    # ### end Alembic commands ###
