"""empty message

Revision ID: 106c1729b110
Revises: 4bf71360fe33
Create Date: 2025-02-03 13:35:50.084872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106c1729b110'
down_revision = '4bf71360fe33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Category_created_on', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('Category_modified_on', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.drop_column('Category_modified_on')
        batch_op.drop_column('Category_created_on')

    # ### end Alembic commands ###
