"""empty message

Revision ID: a1cf0d92f687
Revises: de62537ca484
Create Date: 2025-02-11 13:17:19.554570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1cf0d92f687'
down_revision = 'de62537ca484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('modified_on', sa.String(length=150), nullable=False))
        batch_op.drop_column('Category_modified_on')
        batch_op.drop_column('Category_isDeleted')
        batch_op.drop_column('Category_created_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Category_created_on', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('Category_isDeleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Category_modified_on', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('modified_on')
        batch_op.drop_column('created_on')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
