"""Initial migration.

Revision ID: c432966fda05
Revises: 2ddb050de2b1
Create Date: 2025-02-11 14:04:38.672969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c432966fda05'
down_revision = '2ddb050de2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('modified_on', sa.String(length=150), nullable=False))
        batch_op.drop_column('Product_created_on')
        batch_op.drop_column('Product_modified_on')
        batch_op.drop_column('Product_isDeleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Product_isDeleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Product_modified_on', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('Product_created_on', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('modified_on')
        batch_op.drop_column('created_on')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
