"""empty message

Revision ID: c7ee7b03fe78
Revises: cc0a61311388
Create Date: 2025-02-03 14:35:17.048255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ee7b03fe78'
down_revision = 'cc0a61311388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Product_isDeleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Product_created_on', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('Product_modified_on', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.drop_column('Product_modified_on')
        batch_op.drop_column('Product_created_on')
        batch_op.drop_column('Product_isDeleted')

    # ### end Alembic commands ###
