"""empty message

Revision ID: cc0a61311388
Revises: 106c1729b110
Create Date: 2025-02-03 14:06:45.535932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0a61311388'
down_revision = '106c1729b110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Subcategory_isDeleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Subcategory_created_on', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('Subcategory_modified_on', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_table', schema=None) as batch_op:
        batch_op.drop_column('Subcategory_modified_on')
        batch_op.drop_column('Subcategory_created_on')
        batch_op.drop_column('Subcategory_isDeleted')

    # ### end Alembic commands ###
