"""empty message

Revision ID: de62537ca484
Revises: c7ee7b03fe78
Create Date: 2025-02-10 10:24:50.160904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de62537ca484'
down_revision = 'c7ee7b03fe78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['Category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
